name: Android Deploy Dev
on:
  pull_request:
    types: [review_requested]
    branches: [ dev ]

jobs:
  deploy:
    name: Android Deploy Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - name: Run tests
        run: ./gradlew test

      - name: Run assembleRelease
        run: ./gradlew assembleRelease --stacktrace

      - name: Run build release
        run: ./gradlew bundleRelease

      - name: Upload AAB Bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Sign app APP Bundle
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"

      - name: Deploy Play Store(Test)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText:  ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.beksar.androidci
          releaseFiles: app/build/outputs/bundle/release/*.aab
          inAppUpdatePriority: 2
          status: completed
          track: internal
