name: Android Deploy Check
on:
  pull_request:
    types: [opened]

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  deploy:
    name: Android Pull Request Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 1.8 }

      - name: Run tests
        run: ./gradlew test

      - name: Run assembleRelease
        run: ./gradlew assembleRelease --stacktrace

      - name: Run build release
        run: ./gradlew bundleRelease

      - name: Upload AAB Bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Sign app APP Bundle
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"