name: CI
on:
  #  push:
  #    branches: [ master ]
  pull_request:
    branches: [ dev, master ]
  pull_request_review:
    types:
      - submitted
  workflow_dispatch:

jobs:
  build_apk_aab:
    name: Build release artifacts
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - name: Run tests and build release artifacts
        run: |
          ./gradlew test
          ./gradlew assembleRelease --stacktrace
          ./gradlew bundleRelease

      - name: Upload AAB Bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          output:
          alias: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"





      - name: Deploy market
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText:  ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.beksar.androidci
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: internal
#          inAppUpdatePriority: 2
#          userFraction: 0.33
#          whatsNewDirectory: distribution/whatsnew
#          mappingFile: app/build/outputs/mapping/release/mapping.txt
